/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/openkruise/kruise/pkg/apis/apps/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeStatefulSetRollouts implements StatefulSetRolloutInterface
type FakeStatefulSetRollouts struct {
	Fake *FakeAppsV1alpha1
	ns   string
}

var statefulsetrolloutsResource = schema.GroupVersionResource{Group: "apps.kruise.io", Version: "v1alpha1", Resource: "statefulsetrollouts"}

var statefulsetrolloutsKind = schema.GroupVersionKind{Group: "apps.kruise.io", Version: "v1alpha1", Kind: "StatefulSetRollout"}

// Get takes name of the statefulSetRollout, and returns the corresponding statefulSetRollout object, and an error if there is any.
func (c *FakeStatefulSetRollouts) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.StatefulSetRollout, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(statefulsetrolloutsResource, c.ns, name), &v1alpha1.StatefulSetRollout{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StatefulSetRollout), err
}

// List takes label and field selectors, and returns the list of StatefulSetRollouts that match those selectors.
func (c *FakeStatefulSetRollouts) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.StatefulSetRolloutList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(statefulsetrolloutsResource, statefulsetrolloutsKind, c.ns, opts), &v1alpha1.StatefulSetRolloutList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.StatefulSetRolloutList{ListMeta: obj.(*v1alpha1.StatefulSetRolloutList).ListMeta}
	for _, item := range obj.(*v1alpha1.StatefulSetRolloutList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested statefulSetRollouts.
func (c *FakeStatefulSetRollouts) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(statefulsetrolloutsResource, c.ns, opts))

}

// Create takes the representation of a statefulSetRollout and creates it.  Returns the server's representation of the statefulSetRollout, and an error, if there is any.
func (c *FakeStatefulSetRollouts) Create(ctx context.Context, statefulSetRollout *v1alpha1.StatefulSetRollout, opts v1.CreateOptions) (result *v1alpha1.StatefulSetRollout, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(statefulsetrolloutsResource, c.ns, statefulSetRollout), &v1alpha1.StatefulSetRollout{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StatefulSetRollout), err
}

// Update takes the representation of a statefulSetRollout and updates it. Returns the server's representation of the statefulSetRollout, and an error, if there is any.
func (c *FakeStatefulSetRollouts) Update(ctx context.Context, statefulSetRollout *v1alpha1.StatefulSetRollout, opts v1.UpdateOptions) (result *v1alpha1.StatefulSetRollout, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(statefulsetrolloutsResource, c.ns, statefulSetRollout), &v1alpha1.StatefulSetRollout{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StatefulSetRollout), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeStatefulSetRollouts) UpdateStatus(ctx context.Context, statefulSetRollout *v1alpha1.StatefulSetRollout, opts v1.UpdateOptions) (*v1alpha1.StatefulSetRollout, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(statefulsetrolloutsResource, "status", c.ns, statefulSetRollout), &v1alpha1.StatefulSetRollout{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StatefulSetRollout), err
}

// Delete takes name of the statefulSetRollout and deletes it. Returns an error if one occurs.
func (c *FakeStatefulSetRollouts) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(statefulsetrolloutsResource, c.ns, name), &v1alpha1.StatefulSetRollout{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeStatefulSetRollouts) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(statefulsetrolloutsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.StatefulSetRolloutList{})
	return err
}

// Patch applies the patch and returns the patched statefulSetRollout.
func (c *FakeStatefulSetRollouts) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.StatefulSetRollout, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(statefulsetrolloutsResource, c.ns, name, pt, data, subresources...), &v1alpha1.StatefulSetRollout{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StatefulSetRollout), err
}
